version: '3.8'

services:
  # Next.js Application
  liquor-store:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: liquor-aramac-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_CONVEX_URL=${NEXT_PUBLIC_CONVEX_URL:-https://precise-crane-435.convex.cloud}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=https://liquor.aramac.dev/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=https://liquor.aramac.dev/sign-up
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=https://liquor.aramac.dev/admin
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=https://liquor.aramac.dev/admin
      - NEXT_PUBLIC_APP_URL=https://liquor.aramac.dev
      - NEXT_PUBLIC_DEFAULT_LOCALE=es
      - NEXT_PUBLIC_SUPPORTED_LOCALES=es,en
      - NEXT_PUBLIC_ENABLE_LANGUAGE_DETECTION=true
    volumes:
      - ./logs:/app/logs
    networks:
      - liquor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.liquor.rule=Host(`liquor.aramac.dev`)"
      - "traefik.http.routers.liquor.entrypoints=websecure"
      - "traefik.http.routers.liquor.tls.certresolver=letsencrypt"
      - "traefik.http.services.liquor.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.liquor-rate-limit.ratelimit.burst=100"
      - "traefik.http.middlewares.liquor-rate-limit.ratelimit.average=50"
      - "traefik.http.routers.liquor.middlewares=liquor-rate-limit"

networks:
  liquor-network:
    driver: bridge
    name: liquor-network