// This file is auto-generated by Convex
// It will be replaced when you run `npx convex dev`

export const query = () => {
  throw new Error("Convex server not initialized. Run `npx convex dev` to start development.");
};

export const mutation = () => {
  throw new Error("Convex server not initialized. Run `npx convex dev` to start development.");
};

export const internalQuery = () => {
  throw new Error("Convex server not initialized. Run `npx convex dev` to start development.");
};

export const internalMutation = () => {
  throw new Error("Convex server not initialized. Run `npx convex dev` to start development.");
};

export const action = () => {
  throw new Error("Convex server not initialized. Run `npx convex dev` to start development.");
};

export const internalAction = () => {
  throw new Error("Convex server not initialized. Run `npx convex dev` to start development.");
};

export const httpAction = () => {
  throw new Error("Convex server not initialized. Run `npx convex dev` to start development.");
};